### ISSUE TITLE
[US - 7] persisting data

### ISSUE THREAD

**Issue by codeNilo93** [codeNilo93/Capstone-Project#13]
As a user,
I want the locationCards I created to be saved locally so start I can see them again when opening the app later

## Acceptance Criteria

- [x] locationCards persist

## Tasks

- [x] create a new branch
- [x] build necessary local storage functionality
- [x] update app.js
- [ ] write tests
