### ISSUE TITLE
[US - 02] Form page

### ISSUE THREAD

**Issue by codeNilo93** [codeNilo93/Capstone-Project#2]
As a user,
I want to add cards by using a form page that allows me to fill in the necessary information

## Acceptance Criteria
- [x] input forms
- [x] a submit button that clears input when pressed

## Tasks

- [x] create a new branch
- [x] build header, main, navbar component
- [x] add styling
- [ ] write tests
