### ISSUE TITLE
[US - 4] Routing

### ISSUE THREAD

**Issue by codeNilo93** [codeNilo93/Capstone-Project#3]
As a user,
I want to navigate other pages of the app by clicking on the elements in the navbar

## Acceptance Criteria
- [x] clicking on navbar elements navigates user to corresponding page

## Tasks

- [x] create a new branch
- [x] build router functions
- [x] add styling
- [ ] write tests
