### ISSUE TITLE
[US - ?] Login Page

### ISSUE THREAD

**Issue by codeNilo93** [codeNilo93/Capstone-Project#4]
As a student,
when starting the app, I want to login with my credentials first before entering the home page

## Acceptance Criteria

- [ ] a fitting background image
- [ ] box element with a name form and a submit button
- [ ] a11y (accessibility)
- [ ] upon successful login, user will be navigated to the home page

## Tasks

- [ ] create a new branch
- [ ] build login component & login form component
- [ ] add styling
- [ ] write tests
