### ISSUE TITLE
[US - ?] Card Rating

### ISSUE THREAD

**Issue by codeNilo93** [codeNilo93/Capstone-Project#5]
As a student,
I want to rate the location cards with a 1 -5 star system

## Acceptance Criteria

- [ ] Stars displayed on each card
- [ ] Rating persists

## Tasks

- [ ] create a new branch
- [ ] modify Card component with rating elements & function
- [ ] add styling
- [ ] write tests
