### ISSUE TITLE
[US - ] add navigation bar

### ISSUE THREAD

**Issue by codeNilo93** [codeNilo93/Capstone-Project#5]
### Value Statement (User Story)

As a User, I want to have a navigation bar 
so I can enter different sections of the application

## Acceptance criteria

- [ ] on click the navigation bar will appear/disappear

## Tasks

- [ ] Create feature branch
- [ ] build navigation bar component
- [ ] add components to app
- [ ] add styling

## Complexity (low, medium, high)

medium
