### ISSUE TITLE
[US - 5] Add Cards

### ISSUE THREAD

**Issue by codeNilo93** [codeNilo93/Capstone-Project#8]
As a user,
I want to add more location Cards

## Acceptance Criteria

- [x] on submit, a new location card is created in home with input data

## Tasks

- [x] create a new branch
- [x] modify form page
- [x] add styling
- [ ] write tests
