### ISSUE TITLE
[US - 6] Interactive Map Page

### ISSUE THREAD

**Issue by codeNilo93** [codeNilo93/Capstone-Project#9]
As a user,
I want to have an interactive map that shows me the geographical location of the cards I created

## Acceptance Criteria

- [x] on creation of new card, map will show the location on a map provided by Maps API (Google, the other)

## Tasks

- [x] create a new branch
- [x] create a map page which displays an interactive map
- [x] create the necessary functionalities to display pins at respective coordinates
- [x] modify Cards page
- [x] modify createCard function
- [x] add styling
- [ ] write tests
